CFLAGS = -pedantic --std=c11 -W -Wall
CC     = cc $(CFLAGS)

CXXFLAGS = -W -Wall -std=c++14
CXX    = c++ $(CXXFLAGS)

bit_io.o: bit_io.c bit_io.h Makefile
	$(CC) -c $<

#bit_io.o: bit_io.cpp bit_io.hpp Makefile
#	$(CXX) -c $<

